python3 train.py \
    --dataset_name "rotten-tomatoes" \
    --model_name "modified" \
    --learning_rate 1e-3 \
    --num_layers 2 \
    --hidden_dim 128 \
    --key_dim 32 \
    --value_dim 64 \
    --output_dim 128 \
    --batch_size 32 \
    --num_epochs 20 \
    --save_path "models/rotten-tomatoes/ModifiedRNN_{params}.pt" \
    --use_wandb \
    --fused_projection